name: AI Code Review

# Trigger on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
